version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - 55432:5432
  server:
    depends_on:
      - 'postgres'
    command: bash -c "npm run start:dev"
    volumes:
      - '.:/app'
      - .env:/app/.env
volumes:
  postgres:
