version: '3.7'
services:
  postgres:
    image: postgres:latest
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=video-store
    expose:
      - 5432
    ports:
      - 55432:5432
  web:
    depends_on:
      - postgres
    build: .
    command: bash -c "npm run start:dev"
    volumes:
      - '.:/app'
      - .env:/app/.env
